version: "3.3"

services:

  http:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/"
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - internal_network
    depends_on:
      - db
      - app

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        -   "./docker/db/:/docker-entrypoint-initdb.d/"
    networks:
      - internal_network

  app:
    build:
      args:
        user: ibrahim
        uid: 1000
      dockerfile: docker/php.Dockerfile
      context: ./
    working_dir: /var/www
    volumes:
      - "./:/var/www/"
      - "./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    networks:
      - internal_network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
